{"name": "test_sub[错误样例]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 2", "trace": "self = <pytest_practice.testing.test_calculator_second.TestCalculator object at 0x1118f9a50>, get_cal = <pytest_practice.pythoncode.calculator.Calculator object at 0x1118a0710>, start_cal = None, get_sub = [3, 1, 4]\n\n        @pytest.mark.sub\n    #    @pytest.mark.run(order=1)\n        @pytest.mark.second\n        def test_sub(self,get_cal,start_cal,get_sub):\n            if type(get_sub[0]) is float or type(get_sub[1]) is float:\n                result = round(get_cal.sub(get_sub[0],get_sub[1]),2)\n            else:\n                result = get_cal.sub(get_sub[0], get_sub[1])\n>           assert get_sub[2] == result\nE           assert 4 == 2\n\ntest_calculator_second.py:32: AssertionError"}, "attachments": [{"name": "stdout", "source": "2601840c-9109-401d-8761-f6a4f64bfcab-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_sub", "value": "[3, 1, 4]"}], "start": 1599554105377, "stop": 1599554105377, "uuid": "e69140f9-6f03-4243-97d6-92fd74f0e085", "historyId": "1c94c2e954734a2ce29750fc1b79f54e", "testCaseId": "5b04095fd34f8a95faaa98fb17326b07", "fullName": "pytest_practice.testing.test_calculator_second.TestCalculator#test_sub", "labels": [{"name": "tag", "value": "second"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "sub"}, {"name": "parentSuite", "value": "pytest_practice.testing"}, {"name": "suite", "value": "test_calculator_second"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "17558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_practice.testing.test_calculator_second"}]}