{"name": "test_div[错误样例]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2.0", "trace": "self = <pytest_practice.testing.test_calculator_second.TestCalculator object at 0x111912990>, get_cal = <pytest_practice.pythoncode.calculator.Calculator object at 0x1118a0710>, start_cal = None, get_div = [6, 3, 3]\n\n        @pytest.mark.div\n    #    @pytest.mark.run(order=3)\n        @pytest.mark.fourth\n        def test_div(self,get_cal,start_cal,get_div):\n            # 除数为0时，程序员需要进行异常处理，结果应该为空\n            if get_div[1] == 0:\n                result = None\n            else:\n                result = round(get_cal.div(get_div[0],get_div[1]),2)\n>           assert get_div[2] == result\nE           assert 3 == 2.0\n\ntest_calculator_second.py:23: AssertionError"}, "attachments": [{"name": "stdout", "source": "e4c3654e-b8f2-4fbf-990d-6ea7b09e02a5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_div", "value": "[6, 3, 3]"}], "start": 1599554105463, "stop": 1599554105464, "uuid": "50689f9e-6a93-4944-a91a-7e93d4c2ea4b", "historyId": "d7d08208b0e09262fd2433384de17781", "testCaseId": "9c1dc2518dacbe7d31d32fdc5aa45dd1", "fullName": "pytest_practice.testing.test_calculator_second.TestCalculator#test_div", "labels": [{"name": "tag", "value": "div"}, {"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "fourth"}, {"name": "parentSuite", "value": "pytest_practice.testing"}, {"name": "suite", "value": "test_calculator_second"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "17558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_practice.testing.test_calculator_second"}]}